import { mkdir, readFile, rename, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { pathToFileURL } from 'node:url';
import { configFromEnvironment, discoverProxmox } from '../proxmox/client.js';
import { discoverDocker, dockerConfigFromEnvironment } from '../docker/client.js';
import type { CollectorPayload } from './types.js';

export class CollectorOutbox {
  constructor(private readonly file:string){}
  async load():Promise<CollectorPayload[]>{try{const parsed=JSON.parse(await readFile(this.file,'utf8'));return Array.isArray(parsed.payloads)?parsed.payloads:[];}catch(error){if((error as NodeJS.ErrnoException).code==='ENOENT')return[];throw error;}}
  async save(payloads:CollectorPayload[]){await mkdir(dirname(this.file),{recursive:true});const temporary=`${this.file}.${process.pid}.tmp`;await writeFile(temporary,JSON.stringify({payloads:payloads.slice(-100)},null,2),{mode:0o600});await rename(temporary,this.file);}
}
export async function runCollector(env:NodeJS.ProcessEnv=process.env,once=process.argv.includes('--once')){const configuredUrl=new URL(String(env.SENTINEL_URL||''));if(!['http:','https:'].includes(configuredUrl.protocol)||configuredUrl.username||configuredUrl.password||configuredUrl.pathname!=='/'||configuredUrl.search||configuredUrl.hash)throw new Error('SENTINEL_URL must be an HTTP or HTTPS origin without credentials or a path');const url=configuredUrl.origin;const token=String(env.SENTINEL_COLLECTOR_TOKEN||'');if(token.length<32)throw new Error('SENTINEL_COLLECTOR_TOKEN is missing or invalid');const interval=Number(env.SENTINEL_COLLECTOR_INTERVAL_SECONDS||60);if(!Number.isInteger(interval)||interval<30||interval>3600)throw new Error('Collector interval must be between 30 and 3600 seconds');const outbox=new CollectorOutbox(env.SENTINEL_COLLECTOR_OUTBOX||resolve('.sentinel/collector-outbox.json'));const cycle=async()=>{const queued=await outbox.load();const payload=await collect(env,Math.max(Date.now(),(queued.at(-1)?.sequence||0)+1));queued.push(payload);await outbox.save(queued);await flush(url,token,outbox,queued);};if(once){await cycle();return;}let running=false;const scheduled=async()=>{if(running)return;running=true;try{await cycle()}catch(error){console.error(JSON.stringify({level:'error',message:'collector_cycle_failed',error:error instanceof Error?error.message:String(error)}))}finally{running=false}};await scheduled();return setInterval(()=>void scheduled(),interval*1000);}
async function collect(env:NodeJS.ProcessEnv,sequence:number):Promise<CollectorPayload>{const errors:string[]=[];let proxmox;let docker;const [pve,dockerConfig]=[configFromEnvironment(env),dockerConfigFromEnvironment(env)];if(pve)try{proxmox=await discoverProxmox(pve)}catch(error){errors.push(`Proxmox: ${error instanceof Error?error.message:String(error)}`)}if(dockerConfig)try{docker=await discoverDocker(dockerConfig)}catch(error){errors.push(`Docker: ${error instanceof Error?error.message:String(error)}`)}if(!pve&&!dockerConfig)errors.push('No Proxmox or Docker source is configured');return{sequence,generatedAt:new Date().toISOString(),version:'0.1.0',proxmox,docker,errors};}
async function flush(url:string,token:string,outbox:CollectorOutbox,queued:CollectorPayload[]){while(queued.length){const response=await fetch(`${url}/api/collector/v1/snapshots`,{method:'POST',headers:{authorization:`Bearer ${token}`,'content-type':'application/json'},body:JSON.stringify(queued[0])});if(response.ok||response.status===409){queued.shift();await outbox.save(queued);continue;}throw new Error(`Sentinel returned HTTP ${response.status}`);}}
if(process.argv[1]&&import.meta.url===pathToFileURL(process.argv[1]).href)runCollector().catch(error=>{console.error(error instanceof Error?error.message:'Collector failed');process.exitCode=1;});
