import { mkdtemp, readFile, rm } from 'node:fs/promises';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { afterEach, describe, expect, it } from 'vitest';
import { simulatedDockerInventory } from '../docker/inventory.js';
import { simulatedInventory } from '../proxmox/inventory.js';
import { CollectorAuthError, CollectorReplayError, CollectorService } from './service.js';
import { CollectorOutbox } from './agent.js';
import { CmdbService } from '../cmdb/service.js';

describe('distributed collectors',()=>{
  let directory='';afterEach(async()=>{if(directory)await rm(directory,{recursive:true,force:true});directory='';});
  it('registers a collector, hashes its token, accepts inventory, and detects stale heartbeats',async()=>{directory=await mkdtemp(join(tmpdir(),'sentinel-collector-'));const file=join(directory,'collectors.json');const service=new CollectorService({SENTINEL_COLLECTOR_FILE:file});const registration=await service.register({name:'Basement collector',site:'Home lab',kind:'hybrid',intervalSeconds:30});expect(registration.token).toMatch(/^slc_/);expect(await readFile(file,'utf8')).not.toContain(registration.token);const payload={sequence:1,generatedAt:new Date().toISOString(),version:'0.1.0',proxmox:simulatedInventory(),docker:simulatedDockerInventory(),errors:[]};expect(await service.ingest(registration.token,payload)).toMatchObject({accepted:true,collectorId:registration.collector.id});await expect(service.ingest(registration.token,payload)).rejects.toBeInstanceOf(CollectorReplayError);await expect(service.ingest('invalid',payload)).rejects.toBeInstanceOf(CollectorAuthError);const current=await service.dashboard();expect(current.summary).toMatchObject({collectors:1,sites:1,online:1,resources:13});expect(current.sites[0]).toMatchObject({name:'Home lab',nodes:3,virtualMachines:2,lxcContainers:2,dockerContainers:5});await service.ingest(registration.token,{sequence:2,generatedAt:new Date().toISOString(),version:'0.1.1',errors:['Proxmox API unavailable']});expect((await service.dashboard()).summary).toMatchObject({resources:13,warnings:2});const stale=await service.dashboard(Date.now()+91_000);expect(stale.collectors[0].status).toBe('stale');expect((await service.inventories(Date.now()+91_000))).toHaveLength(0);});
  it('rotates credentials and persists a bounded collector outbox',async()=>{directory=await mkdtemp(join(tmpdir(),'sentinel-collector-'));const service=new CollectorService({SENTINEL_COLLECTOR_FILE:join(directory,'collectors.json')});const first=await service.register({name:'Docker edge',site:'Garage',kind:'docker'});const rotated=await service.rotate(first.collector.id);const payload={sequence:1,generatedAt:new Date().toISOString(),version:'0.1.0',docker:simulatedDockerInventory()};await expect(service.ingest(first.token,payload)).rejects.toBeInstanceOf(CollectorAuthError);await expect(service.ingest(rotated.token,payload)).resolves.toMatchObject({accepted:true});const outbox=new CollectorOutbox(join(directory,'outbox.json'));await outbox.save(Array.from({length:105},(_,index)=>({...payload,sequence:index+1})));expect(await outbox.load()).toHaveLength(100);});
  it('validates registration and collector payloads',async()=>{directory=await mkdtemp(join(tmpdir(),'sentinel-collector-'));const service=new CollectorService({SENTINEL_COLLECTOR_FILE:join(directory,'collectors.json')});await expect(service.register({name:'bad',site:'lab',kind:'other'})).rejects.toThrow(/Kind/);const registration=await service.register({name:'PVE',site:'Lab',kind:'proxmox'});await expect(service.ingest(registration.token,{sequence:1,generatedAt:new Date().toISOString(),version:'0.1.0'})).rejects.toThrow(/requires a Proxmox/);});
  it('reconciles online remote inventory into a collector-only CMDB',async()=>{directory=await mkdtemp(join(tmpdir(),'sentinel-collector-'));const collectors=new CollectorService({SENTINEL_COLLECTOR_FILE:join(directory,'collectors.json')});const registration=await collectors.register({name:'Remote PVE',site:'Branch lab',kind:'proxmox'});await collectors.ingest(registration.token,{sequence:1,generatedAt:new Date().toISOString(),version:'0.1.0',proxmox:simulatedInventory()});const cmdb=new CmdbService({SENTINEL_REAL_CMDB:'true',SENTINEL_CMDB_FILE:join(directory,'cmdb.json')},undefined,undefined,collectors);await cmdb.ready;const remote=cmdb.list().filter(item=>item.attributes.collectorId===registration.collector.id);expect(remote).toHaveLength(8);expect(remote.find(item=>item.class==='node')?.attributes.site).toBe('Branch lab');expect(cmdb.relationships().filter(item=>item.source==='proxmox')).toHaveLength(4);});
});
