import { createHash, randomBytes, timingSafeEqual } from 'node:crypto';
import { resolve } from 'node:path';
import { CollectorStore } from './store.js';
import type { CollectorDashboard, CollectorKind, CollectorPayload, CollectorView, SiteView, StoredCollector } from './types.js';

const kinds:CollectorKind[]=['proxmox','docker','hybrid'];
export class CollectorService {
  private collectors:StoredCollector[]=[];
  private readonly store:CollectorStore;
  private saves:Promise<void>=Promise.resolve();
  readonly ready:Promise<void>;
  constructor(env:NodeJS.ProcessEnv=process.env) { this.store=new CollectorStore(env.SENTINEL_COLLECTOR_FILE||resolve('.sentinel/collectors.json'));this.ready=this.initialize(); }
  private async initialize(){const data=await this.store.load();this.collectors=Array.isArray(data.collectors)?data.collectors:[];}
  async register(input:Record<string,unknown>){await this.ready;if(this.collectors.length>=100)throw new Error('Collector limit reached');const name=field(input.name,'Name',100);const site=field(input.site,'Site',100);const kind=input.kind as CollectorKind;if(!kinds.includes(kind))throw new Error('Kind must be proxmox, docker, or hybrid');const intervalSeconds=Number(input.intervalSeconds??60);if(!Number.isInteger(intervalSeconds)||intervalSeconds<30||intervalSeconds>3600)throw new Error('Interval must be between 30 and 3600 seconds');const token=makeToken();const record:StoredCollector={id:`collector-${crypto.randomUUID()}`,name,site,kind,intervalSeconds,tokenHash:hash(token),createdAt:new Date().toISOString()};this.collectors.push(record);await this.save();return{collector:this.view(record),token};}
  async rotate(id:string){await this.ready;const collector=this.find(id);const token=makeToken();collector.tokenHash=hash(token);await this.save();return{collector:this.view(collector),token};}
  async remove(id:string){await this.ready;const index=this.collectors.findIndex(item=>item.id===id);if(index<0)throw new Error('Collector not found');const[removed]=this.collectors.splice(index,1);await this.save();return{id:removed.id,removed:true};}
  async ingest(token:string,input:unknown){await this.ready;const collector=this.collectors.find(item=>secureEqual(hash(token),item.tokenHash));if(!collector)throw new CollectorAuthError();const payload=validatePayload(input,collector.kind);if(collector.lastSequence!==undefined&&payload.sequence<=collector.lastSequence)throw new CollectorReplayError();collector.lastSeenAt=new Date().toISOString();collector.lastSequence=payload.sequence;collector.lastSnapshot={...payload,proxmox:payload.proxmox||collector.lastSnapshot?.proxmox,docker:payload.docker||collector.lastSnapshot?.docker};await this.save();return{accepted:true,collectorId:collector.id,receivedAt:collector.lastSeenAt};}
  async dashboard(now=Date.now()):Promise<CollectorDashboard>{await this.ready;const collectors=this.collectors.map(item=>this.view(item,now));const siteNames=[...new Set(collectors.map(item=>item.site))].sort();const sites:SiteView[]=siteNames.map(name=>{const members=this.collectors.filter(item=>item.site===name);const views=collectors.filter(item=>item.site===name);return{name,collectors:members.length,online:views.filter(item=>item.status==='online').length,stale:views.filter(item=>item.status==='stale').length,nodes:sum(members,item=>item.lastSnapshot?.proxmox?.summary.nodes||0),virtualMachines:sum(members,item=>item.lastSnapshot?.proxmox?.summary.virtualMachines||0),lxcContainers:sum(members,item=>item.lastSnapshot?.proxmox?.summary.lxcContainers||0),dockerContainers:sum(members,item=>item.lastSnapshot?.docker?.summary.total||0),warnings:sum(views,item=>item.summary.warnings+item.summary.errors)}});return{collectors,sites,summary:{collectors:collectors.length,sites:sites.length,online:collectors.filter(item=>item.status==='online').length,stale:collectors.filter(item=>item.status==='stale').length,never:collectors.filter(item=>item.status==='never').length,resources:sum(collectors,item=>item.summary.proxmoxResources+item.summary.dockerContainers),warnings:sum(collectors,item=>item.summary.warnings+item.summary.errors)}};}
  async inventories(now=Date.now()){await this.ready;return this.collectors.filter(item=>this.view(item,now).status==='online'&&item.lastSnapshot).map(item=>({collector:{id:item.id,name:item.name,site:item.site},snapshot:item.lastSnapshot!}));}
  async prometheus(){const value=await this.dashboard();return`# HELP sentinel_collectors_total Registered remote collectors\n# TYPE sentinel_collectors_total gauge\nsentinel_collectors_total ${value.summary.collectors}\n# HELP sentinel_collectors_online Online remote collectors\n# TYPE sentinel_collectors_online gauge\nsentinel_collectors_online ${value.summary.online}\n# HELP sentinel_collectors_stale Collectors missing their heartbeat deadline\n# TYPE sentinel_collectors_stale gauge\nsentinel_collectors_stale ${value.summary.stale+value.summary.never}\n# HELP sentinel_collector_resources Remote resources in latest snapshots\n# TYPE sentinel_collector_resources gauge\nsentinel_collector_resources ${value.summary.resources}\n`;}
  private view(item:StoredCollector,now=Date.now()):CollectorView{const ageSeconds=item.lastSeenAt?Math.max(0,Math.floor((now-new Date(item.lastSeenAt).getTime())/1000)):null;const status=item.lastSeenAt?(ageSeconds!<=Math.max(90,item.intervalSeconds*3)?'online':'stale'):'never';const snapshot=item.lastSnapshot;return{id:item.id,name:item.name,site:item.site,kind:item.kind,intervalSeconds:item.intervalSeconds,createdAt:item.createdAt,lastSeenAt:item.lastSeenAt,lastSequence:item.lastSequence,status,ageSeconds,version:snapshot?.version||null,summary:{proxmoxResources:snapshot?.proxmox?.resources.length||0,dockerContainers:snapshot?.docker?.containers.length||0,warnings:(snapshot?.proxmox?.summary.warnings||0)+(snapshot?.docker?.summary.unhealthy||0),errors:snapshot?.errors?.length||0}};}
  private find(id:string){const item=this.collectors.find(value=>value.id===id);if(!item)throw new Error('Collector not found');return item;}
  private save(){const snapshot=structuredClone({collectors:this.collectors});const run=()=>this.store.save(snapshot);this.saves=this.saves.then(run,run);return this.saves;}
}
export class CollectorAuthError extends Error{status=401;constructor(){super('Invalid collector token')}}
export class CollectorReplayError extends Error{status=409;constructor(){super('Snapshot sequence was already processed')}}
function field(value:unknown,label:string,max:number){const output=String(value||'').trim();if(!output||output.length>max)throw new Error(`${label} is required and must be at most ${max} characters`);return output;}
function makeToken(){return`slc_${randomBytes(32).toString('base64url')}`;}function hash(value:string){return createHash('sha256').update(value).digest('hex');}function secureEqual(left:string,right:string){const a=Buffer.from(left);const b=Buffer.from(right);return a.length===b.length&&timingSafeEqual(a,b);}function sum<T>(items:T[],value:(item:T)=>number){return items.reduce((total,item)=>total+value(item),0);}
function validatePayload(input:unknown,kind:CollectorKind):CollectorPayload{if(!input||typeof input!=='object'||Array.isArray(input))throw new Error('Snapshot must be an object');const value=input as Partial<CollectorPayload>;if(!Number.isSafeInteger(value.sequence)||Number(value.sequence)<1)throw new Error('Snapshot sequence must be a positive integer');if(!value.generatedAt||!Number.isFinite(new Date(value.generatedAt).getTime()))throw new Error('Snapshot timestamp is invalid');if(new Date(value.generatedAt).getTime()>Date.now()+300_000)throw new Error('Snapshot timestamp is too far in the future');const version=String(value.version||'').trim();if(!version||version.length>40)throw new Error('Collector version is required');const errors=Array.isArray(value.errors)?value.errors.map(item=>String(item).slice(0,500)).slice(0,20):undefined;const failed=Boolean(errors?.length);if(kind==='proxmox'&&!value.proxmox&&!failed)throw new Error('This collector requires a Proxmox inventory');if(kind==='docker'&&!value.docker&&!failed)throw new Error('This collector requires a Docker inventory');if(kind==='hybrid'&&!value.proxmox&&!value.docker&&!failed)throw new Error('This collector requires an inventory');if(value.proxmox&&!validProxmox(value.proxmox))throw new Error('Proxmox inventory is invalid or too large');if(value.docker&&!validDocker(value.docker))throw new Error('Docker inventory is invalid or too large');return{sequence:Number(value.sequence),generatedAt:value.generatedAt,version,proxmox:value.proxmox,docker:value.docker,errors};}
function validProxmox(value:unknown){if(!record(value)||!Array.isArray(value.resources)||value.resources.length>5000||!record(value.summary))return false;const summary=value.summary;return value.resources.every(item=>record(item)&&textValue(item.id)&&textValue(item.name)&&['node','qemu','lxc','storage'].includes(String(item.type))&&textValue(item.state))&&['nodes','virtualMachines','lxcContainers','storagePools','runningWorkloads','stoppedWorkloads','warnings'].every(key=>count(summary[key]));}
function validDocker(value:unknown){if(!record(value)||!Array.isArray(value.containers)||value.containers.length>5000||!record(value.summary))return false;const summary=value.summary;return value.containers.every(item=>record(item)&&textValue(item.id)&&textValue(item.name)&&textValue(item.image)&&textValue(item.state)&&Array.isArray(item.ports))&&['total','running','stopped','healthy','unhealthy','composeProjects'].every(key=>count(summary[key]));}
function record(value:unknown):value is Record<string,unknown>{return Boolean(value)&&typeof value==='object'&&!Array.isArray(value);}function textValue(value:unknown){return typeof value==='string'&&value.length>0&&value.length<=500;}function count(value:unknown){return typeof value==='number'&&Number.isFinite(value)&&value>=0;}
