import type{LogEntry,LogLevel,LogRange,LogSearchFilters,LogSearchResult}from'./types.js';

const ranges:Record<LogRange,number>={'15m':900_000,'1h':3_600_000,'6h':21_600_000,'24h':86_400_000,'7d':604_800_000};
const levels=new Set(['debug','info','warn','error','critical']);
const regexEscape=(value:string)=>value.replace(/[\\^$.*+?()[\]{}|]/g,'\\$&');
const labelValue=(value:string)=>value.replace(/\\/g,'\\\\').replace(/"/g,'\\"').replace(/\n/g,'');
const lineValue=(value:string)=>JSON.stringify(value.slice(0,200));
export class LokiService{
  private readonly url:string|null;private readonly timeoutMs:number;
  constructor(private readonly env:NodeJS.ProcessEnv=process.env){this.url=env.LOKI_URL?.replace(/\/$/,'')||null;this.timeoutMs=Number(env.LOKI_TIMEOUT_MS||5000);if(!Number.isInteger(this.timeoutMs)||this.timeoutMs<500||this.timeoutMs>30_000)throw new Error('Loki timeout must be between 500 and 30000 milliseconds');if(this.url){const parsed=new URL(this.url);if(!['http:','https:'].includes(parsed.protocol))throw new Error('LOKI_URL must use HTTP or HTTPS');if(parsed.protocol==='http:'&&env.LOKI_ALLOW_HTTP!=='true')throw new Error('Plain HTTP Loki connections require LOKI_ALLOW_HTTP=true')}}
  mode(){return this.url?'live' as const:'simulation' as const}
  status(){return{mode:this.mode(),configured:Boolean(this.url),url:this.url?new URL(this.url).origin:null,timeoutMs:this.timeoutMs,retentionManagedBy:'loki'}}
  async search(filters:LogSearchFilters={}):Promise<LogSearchResult>{const range=this.range(filters.range);const limit=Number(filters.limit||200);if(!Number.isInteger(limit)||limit<1||limit>500)throw new Error('Log result limit must be between 1 and 500');for(const value of[filters.level,filters.source,filters.service,filters.search])if(value&&value.length>200)throw new Error('Log filters must be at most 200 characters');if(filters.level&&!levels.has(filters.level))throw new Error('Invalid log level');const end=Date.now(),start=end-ranges[range];const query=this.query(filters);const entries=this.url?await this.live(query,start,end,limit):this.simulated(filters,start,end,limit);return{mode:this.mode(),query,range,start:new Date(start).toISOString(),end:new Date(end).toISOString(),entries,summary:this.summary(entries)}}
  async correlate(ciIds:string[],range:LogRange='6h'){return this.search({ciIds:[...new Set(ciIds.filter(Boolean))].slice(0,20),range,limit:300})}
  private range(value?:string):LogRange{if(!value)return'1h';if(!(value in ranges))throw new Error('Log range must be 15m, 1h, 6h, 24h, or 7d');return value as LogRange}
  private query(filters:LogSearchFilters){const matchers:string[]=[];if(filters.source)matchers.push(`source="${labelValue(filters.source)}"`);if(filters.level)matchers.push(`level="${labelValue(filters.level)}"`);if(filters.service)matchers.push(`service_name="${labelValue(filters.service)}"`);if(filters.ciIds?.length)matchers.push(`ci_id=~"${filters.ciIds.map(item=>regexEscape(item)).join('|')}"`);if(!matchers.length)matchers.push('source=~".+"');return`{${matchers.join(',')}}${filters.search?` |= ${lineValue(filters.search)}`:''}`}
  private async live(query:string,start:number,end:number,limit:number){const endpoint=new URL(`${this.url}/loki/api/v1/query_range`);endpoint.searchParams.set('query',query);endpoint.searchParams.set('start',`${BigInt(start)*1_000_000n}`);endpoint.searchParams.set('end',`${BigInt(end)*1_000_000n}`);endpoint.searchParams.set('limit',String(limit));endpoint.searchParams.set('direction','backward');const response=await fetch(endpoint,{headers:{Accept:'application/json'},signal:AbortSignal.timeout(this.timeoutMs)});if(!response.ok)throw new Error(`Loki query failed with HTTP ${response.status}`);const body=await response.json()as{status?:string;data?:{result?:Array<{stream:Record<string,string>;values:Array<[string,string]>}>}};if(body.status!=='success')throw new Error('Loki returned an unsuccessful response');const entries:LogEntry[]=[];for(const stream of body.data?.result||[])for(const[timestamp,line]of stream.values){const parsed=this.parse(line);entries.push({id:`log-${timestamp}-${entries.length}`,timestamp:new Date(Number(BigInt(timestamp)/1_000_000n)).toISOString(),level:this.level(parsed.level||stream.stream.level),message:String(parsed.message||parsed.msg||line).slice(0,2000),source:stream.stream.source||'unknown',service:String(parsed.service||stream.stream.service_name||stream.stream.unit||''),ciId:String(parsed.ci_id||stream.stream.ci_id||''),host:stream.stream.host||'',labels:stream.stream,raw:line.slice(0,5000)})}return entries.sort((a,b)=>b.timestamp.localeCompare(a.timestamp)).slice(0,limit)}
  private simulated(filters:LogSearchFilters,start:number,end:number,limit:number){const templates=[['info','sentinel-api','service/sentinel-api','http_request completed','docker'],['warn','proxmox','node/pve-01','Storage latency crossed the warning threshold','journal'],['error','media-api','container/media-api','Database connection timed out','docker'],['info','docker','docker-host/sentinel-docker','Container health check recovered','docker'],['critical','idrac-r640','node/r640-01','Power supply redundancy lost','syslog'],['warn','pbs','service/proxmox-backup','Backup verification completed with warnings','journal']]as const;return Array.from({length:36},(_,index)=>{const item=templates[index%templates.length];const timestamp=new Date(end-index*Math.max(30_000,(end-start)/36)).toISOString();return{id:`sim-log-${index}`,timestamp,level:item[0]as LogLevel,message:item[3],source:item[4],service:item[1],ciId:item[2],host:item[1],labels:{source:item[4],service_name:item[1],ci_id:item[2],level:item[0]},raw:JSON.stringify({timestamp,level:item[0],service:item[1],ci_id:item[2],message:item[3]})}}).filter(entry=>(!filters.level||entry.level===filters.level)&&(!filters.source||entry.source===filters.source)&&(!filters.service||entry.service===filters.service)&&(!filters.ciIds?.length||filters.ciIds.includes(entry.ciId))&&(!filters.search||entry.message.toLowerCase().includes(filters.search.toLowerCase()))).slice(0,limit)}
  private parse(line:string):Record<string,unknown>{try{const value=JSON.parse(line);return value&&typeof value==='object'?value:{}}catch{return{}}}private level(value:unknown):LogLevel{const normalized=String(value||'unknown').toLowerCase();return levels.has(normalized)?normalized as LogLevel:'unknown'}private summary(entries:LogEntry[]){return{total:entries.length,errors:entries.filter(item=>item.level==='error'||item.level==='critical').length,warnings:entries.filter(item=>item.level==='warn').length,sources:new Set(entries.map(item=>item.source)).size,services:new Set(entries.map(item=>item.service).filter(Boolean)).size}}
}
