import{mkdtemp,rm}from'node:fs/promises';import{tmpdir}from'node:os';import{join}from'node:path';import{afterEach,describe,expect,it,vi}from'vitest';import{CmdbService}from'../cmdb/service.js';import{HardwareService}from'../hardware/service.js';import{MonitoringService}from'../monitoring/service.js';import{ServiceNowCmdbService}from'./servicenow.js';

const directories:string[]=[];afterEach(async()=>Promise.all(directories.splice(0).map(value=>rm(value,{recursive:true,force:true}))));
async function cmdbServices(){const directory=await mkdtemp(join(tmpdir(),'sentinel-snow-'));directories.push(directory);const monitoring=new MonitoringService({SENTINEL_DATA_FILE:join(directory,'monitoring.json')});const hardware=new HardwareService({SENTINEL_HARDWARE_OPERATIONS_FILE:join(directory,'hardware.json')});const cmdb=new CmdbService({SENTINEL_CMDB_FILE:join(directory,'cmdb.json')},monitoring,hardware);await Promise.all([monitoring.ready,hardware.ready,cmdb.ready]);return{directory,cmdb,hardware}}

describe('ServiceNow CMDB integration',()=>{
  it('previews an IRE synchronization without external access',async()=>{const{directory,cmdb,hardware}=await cmdbServices();const service=new ServiceNowCmdbService(cmdb,hardware,{SENTINEL_SERVICENOW_CMDB_FILE:join(directory,'snow.json')});await service.ready;const run=await service.sync();expect(run).toMatchObject({mode:'simulation',status:'completed',items:cmdb.list().length,failed:0});expect(service.snapshot().mappings).toHaveLength(cmdb.list().length);expect(service.snapshot().mappings[0].operation).toBe('SIMULATED');expect(await service.prometheus()).toContain('sentinel_servicenow_cmdb_last_sync_success 1')});
  it('uses IRE source keys, retains sys_ids, and creates a correlated change',async()=>{const{directory,cmdb,hardware}=await cmdbServices();let payload:{items:Array<{internal_id:string;sys_object_source_info:{source_native_key:string}}>;relations:unknown[]}={items:[],relations:[]};const fetcher=vi.fn(async(input:string|URL|Request,init?:RequestInit)=>{const url=String(input);if(url.includes('identifyreconcile')){payload=JSON.parse(String(init?.body));return Response.json({result:{items:payload.items.map((_,index)=>({operation:'INSERT',sysId:`sys-${index}`,errorCount:0})),relations:[]}})}return Response.json({result:{sys_id:'change-sys',number:'CHG0010001'}})});const service=new ServiceNowCmdbService(cmdb,hardware,{SENTINEL_SERVICENOW_URL:'https://example.service-now.com',SENTINEL_SERVICENOW_TOKEN:'token',SENTINEL_REAL_SERVICENOW_CMDB:'true',SENTINEL_SERVICENOW_CMDB_FILE:join(directory,'snow.json')},fetcher);await service.ready;const run=await service.sync();expect(run.inserted).toBe(cmdb.list().length);expect(payload.items[0].sys_object_source_info.source_native_key).toContain(':');expect(payload.relations.length).toBeGreaterThan(0);const ci=cmdb.list()[0];const change=await service.createChange({ciId:ci.id,shortDescription:'Patch host',description:'Apply approved updates',startsAt:new Date(Date.now()+60_000).toISOString(),endsAt:new Date(Date.now()+3_600_000).toISOString()});expect(change).toMatchObject({number:'CHG0010001',status:'created'});expect(fetcher.mock.calls.at(-1)?.[0]).toContain('/api/now/table/change_request')});
  it('requires credentials before live mode',async()=>{const{cmdb}=await cmdbServices();expect(()=>new ServiceNowCmdbService(cmdb,undefined,{SENTINEL_REAL_SERVICENOW_CMDB:'true'})).toThrow(/requires a URL/)})
});
