import { resolve } from 'node:path';
import { createApp } from './app.js';
import { MonitoringService } from './monitoring/service.js';
import { Store } from './store.js';
import {TelemetryService} from './telemetry/service.js';
import { CmdbService } from './cmdb/service.js';
import { LokiService } from './logging/service.js';
import { HardwareService } from './hardware/service.js';
import { SecurityAuditService } from './security/service.js';
import { BackupService } from './backup/service.js';
import { CollectorService } from './collector/service.js';
import { ServiceNowCmdbService } from './integrations/servicenow.js';
import { configFromEnvironment } from './proxmox/client.js';
import { ProxmoxOperationsService } from './proxmox/operations.js';
import { PbsHealthService } from './pbs/service.js';
import { RecoveryDrillService } from './recovery/drills.js';

const port = Number(process.env.PORT || 4100);
const store = new Store(process.env.DATABASE_PATH || resolve('data/sentinel.db'));
const monitoring = new MonitoringService();
const telemetry=new TelemetryService();
const hardware = new HardwareService();
const collectors = new CollectorService();
const cmdb = new CmdbService(process.env, monitoring, hardware, collectors);
const serviceNow = new ServiceNowCmdbService(cmdb, hardware);
const proxmoxOperations = new ProxmoxOperationsService(configFromEnvironment());
const pbsHealth = new PbsHealthService();
const logs = new LokiService();
const security = new SecurityAuditService();
const backups = new BackupService(store);
const recoveryDrills = new RecoveryDrillService(backups);
createApp(store, monitoring, telemetry, cmdb, logs, hardware, undefined, undefined, security, backups, collectors, serviceNow, proxmoxOperations, pbsHealth, recoveryDrills).listen(port, '0.0.0.0', () => console.log(JSON.stringify({ timestamp: new Date().toISOString(), level: 'info', service: 'sentinel-api', message: 'api_started', port })));
