import type{MonitoringService}from'../monitoring/service.js';import type{RecoveryReadinessService}from'./readiness.js';import type{RecoveryAlertEvaluation,RecoveryAlertStatus}from'./alert-types.js';

type IncidentSink=Pick<MonitoringService,'ready'|'reconcileSystemIncident'|'incidents'>;type Trigger=RecoveryAlertEvaluation['trigger'];
export class RecoveryAlertService{
  readonly ready:Promise<void>;private timer?:NodeJS.Timeout;private queue?:Promise<RecoveryAlertEvaluation>;private lastEvaluatedAt:string|null=null;private lastState:RecoveryAlertStatus['lastState']=null;private lastError='';private readonly enabled:boolean;private readonly intervalSeconds:number;private readonly cooldownSeconds:number;
  constructor(private readonly readiness:Pick<RecoveryReadinessService,'snapshot'>,private readonly monitoring:IncidentSink,env:NodeJS.ProcessEnv=process.env,schedule=true){this.enabled=env.SENTINEL_RECOVERY_ALERTS_ENABLED==='true';this.intervalSeconds=integer(env.SENTINEL_RECOVERY_ALERT_INTERVAL_SECONDS,300,60,86_400);this.cooldownSeconds=integer(env.SENTINEL_RECOVERY_ALERT_COOLDOWN_SECONDS,3600,60,604_800);this.ready=this.initialize(schedule)}
  private async initialize(schedule:boolean){await this.monitoring.ready;if(schedule&&this.enabled){await this.evaluate('startup').catch(()=>undefined);this.timer=setInterval(()=>void this.evaluate('scheduled').catch(()=>undefined),this.intervalSeconds*1000);this.timer.unref()}}
  status():RecoveryAlertStatus{const active=this.monitoring.incidents().find(item=>item.ruleId==='system-recovery-readiness'&&item.status!=='resolved');return{enabled:this.enabled,intervalSeconds:this.intervalSeconds,cooldownSeconds:this.cooldownSeconds,lastEvaluatedAt:this.lastEvaluatedAt,lastState:this.lastState,lastError:this.lastError,activeIncidentId:active?.id||null}}
  snapshot(){return{status:this.status(),incident:this.monitoring.incidents().find(item=>item.ruleId==='system-recovery-readiness'&&item.status!=='resolved')||null}}
  evaluate(trigger:Trigger='manual'){if(!this.enabled)throw new Error('Recovery readiness alerts are disabled');if(!this.queue)this.queue=this.perform(trigger).finally(()=>{this.queue=undefined});return this.queue}
  close(){if(this.timer)clearInterval(this.timer)}
  async prometheus(){await this.ready;const value=this.status();return`# HELP sentinel_recovery_alerts_enabled Whether recovery readiness incident automation is enabled\n# TYPE sentinel_recovery_alerts_enabled gauge\nsentinel_recovery_alerts_enabled ${value.enabled?1:0}\n# HELP sentinel_recovery_alert_monitor_error Whether the last policy evaluation failed\n# TYPE sentinel_recovery_alert_monitor_error gauge\nsentinel_recovery_alert_monitor_error ${value.lastError?1:0}\n`}
  private async perform(trigger:Trigger){try{const readiness=await this.readiness.snapshot(),failed=readiness.checks.filter(item=>item.required&&(item.status==='failed'||item.status==='skipped')),warnings=readiness.checks.filter(item=>item.status==='warning'||!item.required&&item.status==='failed');const detail=failed.length?`Required failures: ${failed.map(item=>item.name).join(', ')}`:warnings.length?`Degraded evidence: ${warnings.map(item=>item.name).join(', ')}`:'All required recovery controls pass';const incident=await this.monitoring.reconcileSystemIncident({key:'recovery-readiness',state:readiness.state,summary:`Recovery readiness is ${readiness.state} with score ${readiness.score}/100. ${detail}.`,cooldownSeconds:this.cooldownSeconds});this.lastEvaluatedAt=new Date().toISOString();this.lastState=readiness.state;this.lastError='';return{trigger,readiness,incident,evaluatedAt:this.lastEvaluatedAt}}catch(value){this.lastError=value instanceof Error?value.message:'Recovery alert evaluation failed';throw value}}
}
function integer(value:string|undefined,fallback:number,min:number,max:number){const result=value===undefined?fallback:Number(value);if(!Number.isInteger(result)||result<min||result>max)throw new Error(`Recovery alert setting must be an integer from ${min} to ${max}`);return result}
