import{describe,expect,it}from'vitest';import{RecoveryReadinessService}from'./readiness.js';
const ready=Promise.resolve();const now=Date.parse('2026-09-05T12:00:00Z');
function sources(overrides:{backup?:Record<string,unknown>;application?:Record<string,unknown>;guest?:Record<string,unknown>;pbs?:Record<string,unknown>}={}){const backup={ready,list:async()=>({replicaConfigured:true,backups:[{createdAt:'2026-09-05T06:00:00Z',verified:true,replicated:true}],...overrides.backup})};const application={ready,snapshot:()=>({runs:[{status:'passed',finishedAt:'2026-09-04T12:00:00Z'}],...overrides.application})};const guest={ready,snapshot:()=>({runs:[{mode:'live',status:'passed',cleanupRequired:false,finishedAt:'2026-09-01T12:00:00Z'}],...overrides.guest})};const pbs={ready,snapshot:()=>({status:{mode:'live'},current:{health:'healthy',serverName:'pbs-1',collectedAt:'2026-09-05T11:55:00Z',summary:{snapshots:14}},...overrides.pbs})};return{backup,application,guest,pbs}}
describe('recovery readiness policy',()=>{
  it('reports ready when all required recovery evidence is current',async()=>{const value=sources();const service=new RecoveryReadinessService(value.backup as never,value.application as never,value.guest as never,value.pbs as never,{SENTINEL_RECOVERY_REQUIRE_REPLICA:'true',SENTINEL_RECOVERY_REQUIRE_GUEST_DRILL:'true',SENTINEL_RECOVERY_REQUIRE_PBS:'true'});const snapshot=await service.snapshot(now);expect(snapshot).toMatchObject({state:'ready',score:100,summary:{passed:6,requiredFailures:0}});expect(await service.prometheus()).toContain('sentinel_recovery_readiness_state{state="ready"} 1')});
  it('fails readiness for stale backups and missing required evidence',async()=>{const value=sources({backup:{replicaConfigured:false,backups:[{createdAt:'2026-09-01T00:00:00Z',verified:true,replicated:null}]},application:{runs:[]},guest:{runs:[]},pbs:{status:{mode:'simulation'}}});const service=new RecoveryReadinessService(value.backup as never,value.application as never,value.guest as never,value.pbs as never,{SENTINEL_RECOVERY_REQUIRE_REPLICA:'true',SENTINEL_RECOVERY_REQUIRE_GUEST_DRILL:'true',SENTINEL_RECOVERY_REQUIRE_PBS:'true'});const snapshot=await service.snapshot(now);expect(snapshot.state).toBe('not-ready');expect(snapshot.summary.requiredFailures).toBe(5);expect(snapshot.checks.find(item=>item.id==='backup-rpo')?.status).toBe('failed')});
  it('keeps optional unavailable integrations neutral but flags live PBS warnings',async()=>{const value=sources({backup:{replicaConfigured:false},guest:{runs:[]},pbs:{current:{health:'warning',serverName:'pbs-1',collectedAt:'2026-09-05T11:55:00Z',summary:{snapshots:14}}}});const service=new RecoveryReadinessService(value.backup as never,value.application as never,value.guest as never,value.pbs as never,{});const snapshot=await service.snapshot(now);expect(snapshot.state).toBe('at-risk');expect(snapshot.score).toBe(95);expect(snapshot.checks.filter(item=>item.status==='skipped')).toHaveLength(2);expect(()=>new RecoveryReadinessService(value.backup as never,value.application as never,value.guest as never,value.pbs as never,{SENTINEL_RECOVERY_RPO_HOURS:'0'})).toThrow(/integer/)});
  it('does not accept a simulation as required guest recovery evidence',async()=>{const value=sources({guest:{runs:[{mode:'simulation',status:'passed',cleanupRequired:false,finishedAt:'2026-09-05T11:00:00Z'}]}});const service=new RecoveryReadinessService(value.backup as never,value.application as never,value.guest as never,value.pbs as never,{SENTINEL_RECOVERY_REQUIRE_GUEST_DRILL:'true'});const snapshot=await service.snapshot(now);expect(snapshot.state).toBe('not-ready');expect(snapshot.checks.find(item=>item.id==='guest-drill')).toMatchObject({status:'skipped',required:true})});
});
