export type MonitorProtocol = 'http' | 'tcp' | 'dns';
export type Monitor = {
  id: string;
  name: string;
  protocol: MonitorProtocol;
  target: string;
  intervalSeconds: number;
  timeoutMs: number;
  enabled: boolean;
  expectedStatus?: number;
  createdAt: string;
};
export type MonitorResult = {
  id: string;
  monitorId: string;
  status: 'up' | 'down';
  latencyMs: number;
  detail: string;
  checkedAt: string;
};
export type MonitorView = Monitor & { lastResult?: MonitorResult; healthScore: number | null; uptimePercent: number | null };
export type AlertSeverity = 'warning' | 'critical';
export type AlertRule = {
  id: string;
  name: string;
  monitorId: string;
  failureThreshold: number;
  cooldownSeconds: number;
  severity: AlertSeverity;
  enabled: boolean;
  suppressedUntil?: string;
  createdAt: string;
};
export type Incident = {
  id: string;
  ruleId: string;
  monitorId: string;
  title: string;
  summary: string;
  severity: AlertSeverity;
  status: 'open' | 'acknowledged' | 'resolved';
  occurrences: number;
  openedAt: string;
  updatedAt: string;
  acknowledgedAt?: string;
  resolvedAt?: string;
  lastNotificationAt?: string;
  externalTicket?: { provider: 'servicenow'; id: string; number: string; url?: string; updatedAt: string };
};
export type NotificationChannel = 'webhook' | 'slack' | 'teams' | 'email' | 'servicenow' | 'simulation';
export type NotificationDelivery = {
  id: string;
  incidentId: string;
  channel: NotificationChannel;
  event: 'opened' | 'reminder' | 'resolved';
  status: 'sent' | 'failed' | 'simulated';
  detail: string;
  attemptedAt: string;
  attempt: number;
  retryOf?: string;
};
export type DependencyMapping = { id: string; monitorId: string; resourceId: string; createdAt: string };
export type RetentionPolicy = { days:number; maxResults:number };
export type MetricRange = '1h'|'6h'|'24h'|'7d'|'30d';
export type MetricPoint = { timestamp:string; checks:number; failures:number; availabilityPercent:number|null; avgLatencyMs:number|null };
export type MetricSummary = { checks:number; failures:number; availabilityPercent:number|null; avgLatencyMs:number|null; p95LatencyMs:number|null };
export type MonitorMetricSeries = { monitorId:string; name:string; protocol:MonitorProtocol; currentStatus:'up'|'down'|'pending'; summary:MetricSummary; points:MetricPoint[] };
export type MetricsSnapshot = { range:MetricRange; start:string; end:string; bucketSeconds:number; retainedResults:number; retention:RetentionPolicy; overall:MetricSummary&{activeIncidents:number;enabledRules:number}; series:MonitorMetricSeries[] };
export type MonitoringData = { monitors: Monitor[]; results: MonitorResult[]; alertRules: AlertRule[]; incidents: Incident[]; deliveries: NotificationDelivery[]; dependencyMappings: DependencyMapping[]; retentionPolicy:RetentionPolicy };
