import{mkdtemp,rm}from'node:fs/promises';import{tmpdir}from'node:os';import{join}from'node:path';import{afterEach,describe,expect,it,vi}from'vitest';import{buildPbsHealth,PbsHealthService}from'./service.js';
const directories:string[]=[];afterEach(async()=>Promise.all(directories.splice(0).map(value=>rm(value,{recursive:true,force:true}))));const settings={intervalSeconds:900,retentionDays:30,snapshotWarningHours:26,snapshotCriticalHours:48,verificationWarningDays:7,gcWarningDays:7,storageWarningPercent:80,storageCriticalPercent:90};
describe('PBS health',()=>{
  it('detects stale snapshots, failed verification, storage pressure, and failed tasks',()=>{const now=Math.floor(Date.now()/1000);const value=buildPbsHealth([{store:'vault',used:95,total:100,avail:5}],{vault:[{'backup-type':'vm','backup-id':'104','backup-time':now-60*3600,verification:{state:'failed'}}]},[{upid:'failed',worker_type:'backup',worker_id:'vm/104',status:'TASK ERROR',starttime:now-3600,endtime:now-3500}],[],[],settings,'live');expect(value.health).toBe('critical');expect(value.summary).toMatchObject({snapshots:1,verificationFailed:1,failedTasks24h:1,storagePressure:1});expect(value.findings.map(item=>item.category)).toEqual(expect.arrayContaining(['datastore','snapshot','verification','task']))});
  it('accepts hyphenated PBS task fields',()=>{const now=Math.floor(Date.now()/1000);const value=buildPbsHealth([{store:'vault',used:10,total:100,avail:90}],{vault:[{'backup-type':'vm','backup-id':'104','backup-time':now,verification:{state:'ok'}}]},[{upid:'failed','worker-type':'backup','worker-id':'vm/104',status:'TASK ERROR',starttime:now-60,endtime:now}],[],[],settings,'live');expect(value.recentTasks[0]).toMatchObject({type:'backup',workerId:'vm/104'});expect(value.summary.failedTasks24h).toBe(1)});
  it('uses the PBS token header and preserves optional endpoint errors',async()=>{const directory=await mkdtemp(join(tmpdir(),'sentinel-pbs-'));directories.push(directory);const fetcher=vi.fn(async(input:string|URL|Request,init?:RequestInit)=>{const url=String(input);expect((init?.headers as Record<string,string>).Authorization).toBe('PBSAPIToken=sentinel@pbs!monitor:secret');if(url.includes('datastore-usage'))return Response.json({data:[{store:'vault',used:10,total:100,avail:90}]});if(url.includes('/snapshots'))return Response.json({data:[{'backup-type':'vm','backup-id':'104','backup-time':Math.floor(Date.now()/1000),verification:{state:'ok'}}]});return new Response('forbidden',{status:403})});const service=new PbsHealthService({PBS_URL:'https://pbs.local:8007',PBS_TOKEN_ID:'sentinel@pbs!monitor',PBS_TOKEN_SECRET:'secret',SENTINEL_PBS_FILE:join(directory,'pbs.json')},fetcher);await service.ready;expect(service.snapshot().current?.summary.snapshots).toBe(1);expect(service.snapshot().current?.collectionErrors).toHaveLength(3)});
  it('provides safe simulation, persistence, and metrics without credentials',async()=>{const directory=await mkdtemp(join(tmpdir(),'sentinel-pbs-'));directories.push(directory);const file=join(directory,'pbs.json');const service=new PbsHealthService({SENTINEL_PBS_FILE:file});await service.ready;expect(service.snapshot().current).toMatchObject({mode:'simulation',serverName:'Sentinel PBS'});expect(await service.prometheus()).toContain('sentinel_pbs_snapshots_total');const reloaded=new PbsHealthService({SENTINEL_PBS_FILE:file});await reloaded.ready;expect(reloaded.snapshot().history).toHaveLength(1)});
  it('requires HTTPS and ordered thresholds',()=>{expect(()=>new PbsHealthService({PBS_URL:'http://pbs.local:8007',PBS_TOKEN_ID:'id',PBS_TOKEN_SECRET:'secret'})).toThrow(/HTTPS/);expect(()=>new PbsHealthService({SENTINEL_PBS_SNAPSHOT_WARNING_HOURS:'48',SENTINEL_PBS_SNAPSHOT_CRITICAL_HOURS:'24'})).toThrow(/greater/)})
});
