import { resolve } from 'node:path';
import type { ProxmoxConfig } from './client.js';
import { ProxmoxOperationsStore } from './operations-store.js';
import type { ProxmoxApiResource } from './types.js';
import type { ProxmoxClusterStatus, ProxmoxClusterTask, ProxmoxHaStatus, ProxmoxOperationsData, ProxmoxOperationsSnapshot, ProxmoxOperationalFinding, ProxmoxReplicationJob } from './operations-types.js';

type Settings={intervalSeconds:number;retentionDays:number;backupWarningHours:number;backupCriticalHours:number;storageWarningPercent:number;storageCriticalPercent:number};

export class ProxmoxOperationsService {
  private data:ProxmoxOperationsData={snapshots:[]};private collection?:Promise<ProxmoxOperationsSnapshot>;private readonly store:ProxmoxOperationsStore;private readonly settings:Settings;readonly ready:Promise<void>;
  constructor(private readonly config:ProxmoxConfig|null,private readonly env:NodeJS.ProcessEnv=process.env,private readonly fetcher:typeof fetch=fetch){this.settings={intervalSeconds:integer(env.SENTINEL_PROXMOX_OPERATIONS_INTERVAL_SECONDS,300,60,86_400),retentionDays:integer(env.SENTINEL_PROXMOX_OPERATIONS_RETENTION_DAYS,30,1,365),backupWarningHours:integer(env.SENTINEL_PROXMOX_BACKUP_WARNING_HOURS,26,1,720),backupCriticalHours:integer(env.SENTINEL_PROXMOX_BACKUP_CRITICAL_HOURS,48,2,1440),storageWarningPercent:integer(env.SENTINEL_PROXMOX_STORAGE_WARNING_PERCENT,80,1,99),storageCriticalPercent:integer(env.SENTINEL_PROXMOX_STORAGE_CRITICAL_PERCENT,90,2,100)};if(this.settings.backupCriticalHours<=this.settings.backupWarningHours)throw new Error('Backup critical hours must be greater than warning hours');if(this.settings.storageCriticalPercent<=this.settings.storageWarningPercent)throw new Error('Storage critical percent must be greater than warning percent');this.store=new ProxmoxOperationsStore(env.SENTINEL_PROXMOX_OPERATIONS_FILE||resolve('.sentinel/proxmox-operations.json'));this.ready=this.initialize()}
  private async initialize(){this.data=await this.store.load();this.prune();if(!this.data.snapshots.length)await this.collect();const timer=setInterval(()=>void this.collect().catch(()=>undefined),this.settings.intervalSeconds*1000);timer.unref()}
  status(){return{mode:this.config?'live' as const:'simulation' as const,intervalSeconds:this.settings.intervalSeconds,retentionDays:this.settings.retentionDays,backupWarningHours:this.settings.backupWarningHours,backupCriticalHours:this.settings.backupCriticalHours,storageWarningPercent:this.settings.storageWarningPercent,storageCriticalPercent:this.settings.storageCriticalPercent,lastCollectedAt:this.data.snapshots[0]?.collectedAt||null}}
  snapshot(){return{status:this.status(),current:this.data.snapshots[0]||null,history:this.data.snapshots.slice(0,288)}}
  collect(){if(!this.collection)this.collection=this.performCollection().finally(()=>{this.collection=undefined});return this.collection}
  private async performCollection(){const snapshot=this.config?await this.collectLive(this.config):simulatedProxmoxOperations(this.settings);this.data.snapshots.unshift(snapshot);this.prune();await this.store.save(this.data);return snapshot}
  private async collectLive(config:ProxmoxConfig){const errors:string[]=[];const required=await Promise.all([request<ProxmoxClusterStatus[]>(config,'/cluster/status',this.fetcher),request<ProxmoxApiResource[]>(config,'/cluster/resources?type=storage',this.fetcher)]);const optional=await Promise.all([optionalRequest<ProxmoxClusterTask[]>(config,'/cluster/tasks?limit=200',this.fetcher,errors,'tasks'),optionalRequest<ProxmoxHaStatus[]>(config,'/cluster/ha/status/current',this.fetcher,errors,'HA'),optionalRequest<ProxmoxReplicationJob[]>(config,'/cluster/replication',this.fetcher,errors,'replication')]);return buildOperations(required[0],required[1],optional[0]||[],optional[1]||[],optional[2]||[],this.settings,'live',errors)}
  private prune(){const cutoff=Date.now()-this.settings.retentionDays*86_400_000;this.data.snapshots=this.data.snapshots.filter(item=>new Date(item.collectedAt).getTime()>=cutoff).slice(0,10_000)}
  async prometheus(){await this.ready;const value=this.data.snapshots[0];if(!value)return'';return`# HELP sentinel_proxmox_operations_health Proxmox operational health by state\n# TYPE sentinel_proxmox_operations_health gauge\n${['healthy','warning','critical','unknown'].map(state=>`sentinel_proxmox_operations_health{state="${state}"} ${value.health===state?1:0}`).join('\n')}\n# HELP sentinel_proxmox_quorate Whether the Proxmox cluster has quorum\n# TYPE sentinel_proxmox_quorate gauge\nsentinel_proxmox_quorate ${value.quorum.quorate===null?-1:value.quorum.quorate?1:0}\n# HELP sentinel_proxmox_failed_tasks_24h Failed Proxmox tasks during the last 24 hours\n# TYPE sentinel_proxmox_failed_tasks_24h gauge\nsentinel_proxmox_failed_tasks_24h ${value.summary.failedTasks24h}\n# HELP sentinel_proxmox_backup_age_hours Hours since the last successful backup task\n# TYPE sentinel_proxmox_backup_age_hours gauge\nsentinel_proxmox_backup_age_hours ${value.backup.ageHours??-1}\n# HELP sentinel_proxmox_storage_usage_percent Proxmox storage utilization\n# TYPE sentinel_proxmox_storage_usage_percent gauge\n${value.storage.map(item=>`sentinel_proxmox_storage_usage_percent{storage="${label(item.name)}",node="${label(item.node)}"} ${item.usagePercent}`).join('\n')}\n`}
}

export function buildOperations(cluster:ProxmoxClusterStatus[],resources:ProxmoxApiResource[],tasks:ProxmoxClusterTask[],ha:ProxmoxHaStatus[],replication:ProxmoxReplicationJob[],settings:Settings,mode:'simulation'|'live',collectionErrors:string[]=[]):ProxmoxOperationsSnapshot{
  const now=Date.now();const clusterInfo=cluster.find(item=>item.type==='cluster');const nodeRows=cluster.filter(item=>item.type==='node');const quorate=clusterInfo?.quorate===undefined?null:clusterInfo.quorate===1;const findings:ProxmoxOperationalFinding[]=[];if(quorate===false)findings.push(finding('quorum','critical','Cluster quorum lost','The Proxmox cluster is not quorate. Avoid configuration changes until quorum is restored.','cluster'));
  for(const node of nodeRows.filter(item=>item.online===0))findings.push(finding('node','critical',`${node.name||node.node||'Node'} is offline`,'A cluster member is not reporting online.',`node/${node.name||node.node}`));
  const storage=resources.filter(item=>item.type==='storage').map(item=>{const usage=percent(item.disk,item.maxdisk);const health=item.status&&item.status!=='available'?'critical':usage>=settings.storageCriticalPercent?'critical':usage>=settings.storageWarningPercent?'warning':'healthy';if(health!=='healthy')findings.push(finding('storage',health,`${item.name||item.id} storage ${health==='critical'?'critical':'pressure'}`,item.status&&item.status!=='available'?`Storage state is ${item.status}.`:`Utilization is ${usage}%.`,item.id));return{id:item.id,name:item.name||item.id.replace(/^storage\//,''),node:item.node||'cluster',state:item.status||'unknown',usedBytes:item.disk||0,totalBytes:item.maxdisk||0,usagePercent:usage,health}as const});
  const normalizedTasks=tasks.map(task=>normalizeTask(task)).sort((a,b)=>b.startedAt.localeCompare(a.startedAt));const recentTasks=normalizedTasks.filter(item=>now-new Date(item.startedAt).getTime()<=86_400_000);const failedTasks=recentTasks.filter(item=>failedStatus(item.status));for(const task of failedTasks.slice(0,20))findings.push(finding('task','warning',`${task.type} task failed on ${task.node}`,`Task ended with ${task.status}.`,task.id));
  const backups=normalizedTasks.filter(item=>item.type==='vzdump');const recentBackups=recentTasks.filter(item=>item.type==='vzdump');const successfulBackups=backups.filter(item=>!failedStatus(item.status)&&item.endedAt);const lastSuccessfulAt=successfulBackups[0]?.endedAt||null;const ageHours=lastSuccessfulAt?round((now-new Date(lastSuccessfulAt).getTime())/3_600_000):null;const backupHealth=ageHours===null?'unknown':ageHours>=settings.backupCriticalHours?'critical':ageHours>=settings.backupWarningHours?'warning':'healthy';if(backupHealth==='critical'||backupHealth==='warning')findings.push(finding('backup',backupHealth,'Backup freshness outside target',`The latest successful backup is ${ageHours} hours old.`));if(ageHours===null)findings.push(finding('backup','warning','No successful backup found','No successful vzdump task was returned in the available task history.'));
  const haRows=ha.filter(item=>item.type==='node'||item.type==='service').map(item=>{const state=item.status||'unknown';const health=/started|online|idle/i.test(state)?'healthy':'warning';if(health==='warning')findings.push(finding('ha','warning',`HA ${item.sid||item.node||item.id||'resource'} is ${state}`,'Review the Proxmox HA manager state.',item.sid||item.id));return{id:item.sid||item.id||`${item.type}-${item.node}`,kind:item.type==='service'?'service':'node',node:item.node||'cluster',state,health}as const});
  const replicationRows=replication.map(item=>({id:item.id||'unknown',source:item.source||'unknown',target:item.target||'unknown',schedule:item.schedule||'unknown',enabled:item.disable!==1}));const critical=findings.filter(item=>item.severity==='critical').length;const warnings=findings.filter(item=>item.severity==='warning').length;const health=critical?'critical':warnings?'warning':'healthy';return{mode,collectedAt:new Date().toISOString(),clusterName:clusterInfo?.name||'Proxmox cluster',health,quorum:{quorate,nodesOnline:nodeRows.filter(item=>item.online===1).length,nodesTotal:nodeRows.length,expectedVotes:numberOrNull(clusterInfo?.expected_votes),totalVotes:numberOrNull(clusterInfo?.total_votes)},storage,recentTasks:recentTasks.slice(0,50),backup:{lastSuccessfulAt,ageHours,successful24h:recentBackups.filter(item=>!failedStatus(item.status)&&item.endedAt).length,failed24h:recentBackups.filter(item=>failedStatus(item.status)).length,health:backupHealth},ha:haRows,replication:replicationRows,findings,collectionErrors,summary:{warnings,critical,storagePressure:storage.filter(item=>item.health==='warning'||item.health==='critical').length,failedTasks24h:failedTasks.length,haProblems:haRows.filter(item=>item.health!=='healthy').length,replicationJobs:replicationRows.filter(item=>item.enabled).length}}
}

export function simulatedProxmoxOperations(settings:Settings):ProxmoxOperationsSnapshot{const now=Math.floor(Date.now()/1000);return buildOperations([{type:'cluster',name:'Sentinel homelab',quorate:1,nodes:3,expected_votes:3,total_votes:3},{type:'node',name:'pve-01',online:1},{type:'node',name:'pve-02',online:1},{type:'node',name:'pve-03',online:1}],[{id:'storage/local-zfs',type:'storage',name:'local-zfs',node:'pve-02',status:'available',disk:8_900_000_000_000,maxdisk:10_000_000_000_000},{id:'storage/backups',type:'storage',name:'backups',node:'pve-01',status:'available',disk:4_100_000_000_000,maxdisk:12_000_000_000_000}],[{upid:'UPID:pve-01:backup',node:'pve-01',type:'vzdump',user:'backup@pam',status:'OK',starttime:now-29_000,endtime:now-28_800},{upid:'UPID:pve-02:migrate',node:'pve-02',type:'qmigrate',user:'root@pam',status:'OK',starttime:now-7200,endtime:now-7100}],[{type:'node',node:'pve-01',status:'online'},{type:'node',node:'pve-02',status:'online'},{type:'node',node:'pve-03',status:'online'},{type:'service',sid:'vm:104',node:'pve-02',status:'started'}],[{id:'201-0',source:'pve-03',target:'pve-01',schedule:'*/15',disable:0}],settings,'simulation')}

async function request<T>(config:ProxmoxConfig,path:string,fetcher:typeof fetch){const response=await fetcher(`${config.baseUrl}/api2/json${path}`,{headers:{Authorization:`PVEAPIToken=${config.tokenId}=${config.tokenSecret}`},signal:AbortSignal.timeout(15_000)});if(!response.ok)throw new Error(`Proxmox API returned HTTP ${response.status} for ${path.split('?')[0]}`);return(await response.json()as{data:T}).data}
async function optionalRequest<T>(config:ProxmoxConfig,path:string,fetcher:typeof fetch,errors:string[],name:string){try{return await request<T>(config,path,fetcher)}catch(error){errors.push(`${name}: ${error instanceof Error?error.message:'collection failed'}`);return null}}
function normalizeTask(task:ProxmoxClusterTask){const start=task.starttime||0;const end=task.endtime;return{id:task.upid||task.id||crypto.randomUUID(),node:task.node||'cluster',type:task.type||'unknown',user:task.user||'unknown',status:task.status||'running',startedAt:new Date(start*1000).toISOString(),endedAt:end?new Date(end*1000).toISOString():undefined,durationSeconds:end&&start?end-start:undefined}}
function failedStatus(value:string){return !/^(OK|running)$/i.test(value)}function percent(value=0,total=0){return total?round(value/total*100):0}function round(value:number){return Math.round(value*100)/100}function numberOrNull(value?:number){return Number.isFinite(value)?Number(value):null}function finding(category:ProxmoxOperationalFinding['category'],severity:ProxmoxOperationalFinding['severity'],title:string,detail:string,resourceId?:string):ProxmoxOperationalFinding{return{id:`${category}-${resourceId||title}`.toLowerCase().replace(/[^a-z0-9-]+/g,'-'),category,severity,title,detail,resourceId}}function label(value:string){return value.replace(/\\/g,'\\\\').replace(/"/g,'\\"').replace(/\n/g,'')}
function integer(value:string|undefined,fallback:number,min:number,max:number){const result=value===undefined?fallback:Number(value);if(!Number.isInteger(result)||result<min||result>max)throw new Error(`Proxmox operations setting must be an integer from ${min} to ${max}`);return result}
