import {rangeConfig} from '../metrics/analytics.js';
import type {MetricRange} from '../monitoring/types.js';
import type {TelemetryPoint,TelemetrySample,TelemetrySnapshot} from './types.js';

const average=(values:Array<number|null>)=>{const valid=values.filter((value):value is number=>value!==null);return valid.length?Math.round(valid.reduce((sum,value)=>sum+value,0)/valid.length*100)/100:null};
export function buildTelemetryMetrics(samples:TelemetrySample[],range:MetricRange='24h',now=Date.now()):TelemetrySnapshot{const config=rangeConfig[range];const start=now-config.milliseconds;const bucketMs=config.bucketSeconds*1000;const bucketCount=Math.ceil(config.milliseconds/bucketMs);const relevant=samples.filter(sample=>{const time=new Date(sample.collectedAt).getTime();return time>=start&&time<=now});const ids=[...new Set(samples.map(sample=>sample.resourceId))];const series=ids.map(resourceId=>{const all=samples.filter(sample=>sample.resourceId===resourceId);const latest=all[0];const buckets:TelemetrySample[][]=Array.from({length:bucketCount},()=>[]);for(const sample of relevant.filter(item=>item.resourceId===resourceId)){const index=Math.min(bucketCount-1,Math.floor((new Date(sample.collectedAt).getTime()-start)/bucketMs));if(index>=0)buckets[index].push(sample)}const points:TelemetryPoint[]=buckets.map((bucket,index)=>({timestamp:new Date(start+index*bucketMs).toISOString(),samples:bucket.length,cpuPercent:average(bucket.map(item=>item.cpuPercent)),memoryPercent:average(bucket.map(item=>item.memoryPercent)),diskPercent:average(bucket.map(item=>item.diskPercent)),networkRxBytesPerSecond:average(bucket.map(item=>item.networkRxBytesPerSecond)),networkTxBytesPerSecond:average(bucket.map(item=>item.networkTxBytesPerSecond)),diskReadBytesPerSecond:average(bucket.map(item=>item.diskReadBytesPerSecond)),diskWriteBytesPerSecond:average(bucket.map(item=>item.diskWriteBytesPerSecond))}));return{resourceId,name:latest.name,type:latest.type,source:latest.source,state:latest.state,latest,points}});return{range,start:new Date(start).toISOString(),end:new Date(now).toISOString(),bucketSeconds:config.bucketSeconds,summary:{resources:series.length,proxmoxResources:series.filter(item=>item.source==='proxmox').length,containers:series.filter(item=>item.type==='container').length,warningResources:series.filter(item=>item.latest.cpuPercent>=85||(item.latest.memoryPercent||0)>=90||(item.latest.diskPercent||0)>=90).length,sampleCount:relevant.length},series};}

const label=(value:string)=>value.replace(/\\/g,'\\\\').replace(/\n/g,'\\n').replace(/"/g,'\\"');
export function telemetryPrometheus(samples:TelemetrySample[]){const latest=new Map<string,TelemetrySample>();for(const sample of samples)if(!latest.has(sample.resourceId))latest.set(sample.resourceId,sample);const lines=['# HELP sentinel_resource_cpu_percent Current resource CPU utilization.','# TYPE sentinel_resource_cpu_percent gauge'];for(const sample of latest.values()){const labels=`resource_id="${label(sample.resourceId)}",name="${label(sample.name)}",type="${sample.type}",source="${sample.source}"`;lines.push(`sentinel_resource_cpu_percent{${labels}} ${sample.cpuPercent}`,`sentinel_resource_memory_percent{${labels}} ${sample.memoryPercent??0}`,`sentinel_resource_disk_percent{${labels}} ${sample.diskPercent??0}`,`sentinel_resource_network_receive_bytes_per_second{${labels}} ${sample.networkRxBytesPerSecond??0}`,`sentinel_resource_network_transmit_bytes_per_second{${labels}} ${sample.networkTxBytesPerSecond??0}`,`sentinel_resource_disk_read_bytes_per_second{${labels}} ${sample.diskReadBytesPerSecond??0}`,`sentinel_resource_disk_write_bytes_per_second{${labels}} ${sample.diskWriteBytesPerSecond??0}`)}return `${lines.join('\n')}\n`;}
