import path from 'node:path';
import {collectDockerStats,discoverDocker,dockerConfigFromEnvironment} from '../docker/client.js';
import {simulatedDockerInventory} from '../docker/inventory.js';
import {configFromEnvironment,discoverProxmox} from '../proxmox/client.js';
import {simulatedInventory} from '../proxmox/inventory.js';
import {isMetricRange} from '../metrics/analytics.js';
import {buildTelemetryMetrics,telemetryPrometheus} from './analytics.js';
import {TelemetryStore} from './store.js';
import type {MetricRange} from '../monitoring/types.js';
import type {RawTelemetry,TelemetryData,TelemetrySample} from './types.js';

const percent=(used?:number,total?:number)=>used!==undefined&&total?Math.round(used/total*10_000)/100:null;
export class TelemetryService{private data:TelemetryData={samples:[]};private readonly store:TelemetryStore;private readonly simulate:boolean;private readonly intervalSeconds:number;private lastError='';private collecting?:Promise<TelemetrySample[]>;readonly ready:Promise<void>;
  constructor(private readonly env:NodeJS.ProcessEnv=process.env){this.simulate=env.SENTINEL_REAL_TELEMETRY!=='true';this.intervalSeconds=Number(env.SENTINEL_TELEMETRY_INTERVAL_SECONDS||60);if(!Number.isInteger(this.intervalSeconds)||this.intervalSeconds<30||this.intervalSeconds>3600)throw new Error('Telemetry interval must be between 30 and 3600 seconds');this.store=new TelemetryStore(env.SENTINEL_TELEMETRY_FILE||path.resolve('.sentinel/telemetry.json'));this.ready=this.initialize()}
  private async initialize(){this.data=await this.store.load();this.prune();if(!this.data.samples.length)await this.collect();const timer=setInterval(()=>void this.collect().catch(error=>{this.lastError=error instanceof Error?error.message:'Telemetry collection failed'}),this.intervalSeconds*1000);timer.unref()}
  mode(){return this.simulate?'simulation':'live'} status(){const latest=this.data.samples[0];return{mode:this.mode(),intervalSeconds:this.intervalSeconds,lastCollectedAt:latest?.collectedAt||null,lastError:this.lastError,resources:new Set(this.data.samples.map(sample=>sample.resourceId)).size,samples:this.data.samples.length}}
  metrics(rangeValue='24h'){if(!isMetricRange(rangeValue))throw new Error('Range must be 1h, 6h, 24h, 7d, or 30d');return buildTelemetryMetrics(this.data.samples,rangeValue as MetricRange)} prometheus(){return telemetryPrometheus(this.data.samples)}
  async collect(){if(this.collecting)return this.collecting;this.collecting=this.performCollect();try{return await this.collecting}finally{this.collecting=undefined}}
  private async performCollect(){const raw=this.simulate?this.simulatedRaw():await this.liveRaw();const samples=raw.map(item=>this.withRates(item));this.data.samples.unshift(...samples);this.prune();await this.store.save(this.data);this.lastError='';return samples}
  private withRates(raw:RawTelemetry):TelemetrySample{const previous=this.data.samples.find(sample=>sample.resourceId===raw.resourceId);const elapsed=previous?(new Date(raw.collectedAt).getTime()-new Date(previous.collectedAt).getTime())/1000:0;const rate=(current:number|null,prior:number|null)=>elapsed>0&&current!==null&&prior!==null&&current>=prior?Math.round((current-prior)/elapsed):null;return{...raw,id:`telemetry-${crypto.randomUUID()}`,networkRxBytesPerSecond:rate(raw.networkRxBytesTotal,previous?.networkRxBytesTotal??null),networkTxBytesPerSecond:rate(raw.networkTxBytesTotal,previous?.networkTxBytesTotal??null),diskReadBytesPerSecond:rate(raw.diskReadBytesTotal,previous?.diskReadBytesTotal??null),diskWriteBytesPerSecond:rate(raw.diskWriteBytesTotal,previous?.diskWriteBytesTotal??null)}}
  private prune(){const cutoff=Date.now()-30*86_400_000;this.data.samples=this.data.samples.filter(sample=>new Date(sample.collectedAt).getTime()>=cutoff).slice(0,100_000)}
  private proxmoxRaw(inventory:Awaited<ReturnType<typeof discoverProxmox>>,now:string):RawTelemetry[]{return inventory.resources.filter(resource=>resource.type!=='storage').map(resource=>({resourceId:resource.id,name:resource.name,type:resource.type==='qemu'?'vm':resource.type as 'node'|'lxc',source:'proxmox',state:resource.state,cpuPercent:resource.cpuPercent||0,memoryPercent:percent(resource.memoryUsedBytes,resource.memoryTotalBytes),diskPercent:percent(resource.diskUsedBytes,resource.diskTotalBytes),networkRxBytesTotal:resource.networkRxBytes??null,networkTxBytesTotal:resource.networkTxBytes??null,diskReadBytesTotal:null,diskWriteBytesTotal:null,collectedAt:now}))}
  private simulatedRaw(){const timestamp=Date.now();const now=new Date(timestamp).toISOString();const proxmox=this.proxmoxRaw(simulatedInventory(),now).map((item,index)=>({...item,cpuPercent:Math.max(1,Math.round((item.cpuPercent+Math.sin(timestamp/120_000+index)*8)*100)/100),networkRxBytesTotal:item.networkRxBytesTotal===null?null:item.networkRxBytesTotal+Math.floor(timestamp/1000)*(12_000+index*2_000),networkTxBytesTotal:item.networkTxBytesTotal===null?null:item.networkTxBytesTotal+Math.floor(timestamp/1000)*(5_000+index*1_000)}));const docker=simulatedDockerInventory().containers.map((container,index):RawTelemetry=>({resourceId:`container/${container.id}`,name:container.composeService||container.name,type:'container',source:'docker',state:container.state,cpuPercent:container.state==='running'?Math.round((8+index*6+Math.sin(timestamp/90_000+index)*4)*100)/100:0,memoryPercent:container.state==='running'?Math.round((22+index*9)*100)/100:0,diskPercent:null,networkRxBytesTotal:1_000_000+Math.floor(timestamp/1000)*(3_000+index*800),networkTxBytesTotal:500_000+Math.floor(timestamp/1000)*(1_500+index*400),diskReadBytesTotal:2_000_000+Math.floor(timestamp/1000)*(800+index*100),diskWriteBytesTotal:1_000_000+Math.floor(timestamp/1000)*(500+index*80),collectedAt:now}));return[...proxmox,...docker]}
  private async liveRaw(){const now=new Date().toISOString();const output:RawTelemetry[]=[];const proxmoxConfig=configFromEnvironment(this.env);if(proxmoxConfig)output.push(...this.proxmoxRaw(await discoverProxmox(proxmoxConfig),now));const dockerConfig=dockerConfigFromEnvironment(this.env);if(dockerConfig){const inventory=await discoverDocker(dockerConfig);const running=inventory.containers.filter(container=>container.state==='running');const stats=await collectDockerStats(dockerConfig,running.map(container=>container.id));for(const stat of stats){const container=running.find(item=>item.id===stat.containerId)!;output.push({resourceId:`container/${container.id}`,name:container.composeService||container.name,type:'container',source:'docker',state:container.state,cpuPercent:stat.cpuPercent,memoryPercent:percent(stat.memoryUsedBytes,stat.memoryLimitBytes),diskPercent:null,networkRxBytesTotal:stat.networkRxBytes,networkTxBytesTotal:stat.networkTxBytes,diskReadBytesTotal:stat.diskReadBytes,diskWriteBytesTotal:stat.diskWriteBytes,collectedAt:now})}}if(!output.length)throw new Error('Live telemetry requires a configured Proxmox or Docker connection');return output}
}
