import{createHash}from'node:crypto';import type{MonitoringService}from'../monitoring/service.js';import type{Incident}from'../monitoring/types.js';import type{CapacityForecastService}from'./forecast.js';import type{CapacityAlertEvaluation,CapacityAlertState,CapacityAlertStatus}from'./alert-types.js';import type{CapacityConfidence,CapacityForecast}from'./types.js';

type IncidentSink=Pick<MonitoringService,'ready'|'reconcileSystemIncident'|'incidents'>;type Trigger=CapacityAlertEvaluation['trigger'];const confidenceRank:Record<CapacityConfidence,number>={low:0,medium:1,high:2};
export class CapacityAlertService{readonly ready:Promise<void>;private timer?:NodeJS.Timeout;private queue?:Promise<CapacityAlertEvaluation>;private lastEvaluatedAt:string|null=null;private lastState:CapacityAlertState|null=null;private lastError='';private eligibleForecasts=0;private readonly enabled:boolean;private readonly intervalSeconds:number;private readonly cooldownSeconds:number;private readonly minimumConfidence:CapacityConfidence;
  constructor(private readonly forecasts:Pick<CapacityForecastService,'snapshot'>,private readonly monitoring:IncidentSink,env:NodeJS.ProcessEnv=process.env,schedule=true){this.enabled=env.SENTINEL_CAPACITY_ALERTS_ENABLED==='true';this.intervalSeconds=integer(env.SENTINEL_CAPACITY_ALERT_INTERVAL_SECONDS,300,60,86_400);this.cooldownSeconds=integer(env.SENTINEL_CAPACITY_ALERT_COOLDOWN_SECONDS,3600,60,604_800);this.minimumConfidence=confidence(env.SENTINEL_CAPACITY_ALERT_MIN_CONFIDENCE||'high');this.ready=this.initialize(schedule)}
  private async initialize(schedule:boolean){await this.monitoring.ready;if(schedule&&this.enabled){await this.evaluate('startup').catch(()=>undefined);this.timer=setInterval(()=>void this.evaluate('scheduled').catch(()=>undefined),this.intervalSeconds*1000);this.timer.unref()}}
  status():CapacityAlertStatus{return{enabled:this.enabled,intervalSeconds:this.intervalSeconds,cooldownSeconds:this.cooldownSeconds,minimumConfidence:this.minimumConfidence,lastEvaluatedAt:this.lastEvaluatedAt,lastState:this.lastState,lastError:this.lastError,eligibleForecasts:this.eligibleForecasts,activeIncidents:this.active().length}}
  snapshot(){return{status:this.status(),incidents:this.active()}}
  evaluate(trigger:Trigger='manual'){if(!this.enabled)throw new Error('Capacity alerts are disabled');if(!this.queue)this.queue=this.perform(trigger).finally(()=>{this.queue=undefined});return this.queue}
  close(){if(this.timer)clearInterval(this.timer)}
  async prometheus(){await this.ready;const value=this.status();return`# HELP sentinel_capacity_alerts_enabled Whether capacity incident automation is enabled\n# TYPE sentinel_capacity_alerts_enabled gauge\nsentinel_capacity_alerts_enabled ${value.enabled?1:0}\n# HELP sentinel_capacity_alert_active_incidents Active forecast-driven capacity incidents\n# TYPE sentinel_capacity_alert_active_incidents gauge\nsentinel_capacity_alert_active_incidents ${value.activeIncidents}\n# HELP sentinel_capacity_alert_monitor_error Whether the last capacity alert evaluation failed\n# TYPE sentinel_capacity_alert_monitor_error gauge\nsentinel_capacity_alert_monitor_error ${value.lastError?1:0}\n`}
  private active(){return this.monitoring.incidents().filter(item=>item.ruleId.startsWith('system-capacity-')&&item.status!=='resolved')}
  private eligible(item:CapacityForecast,threshold:number){const observed=item.currentPercent!==null&&item.currentPercent>=threshold;return(item.state==='critical'||item.state==='warning')&&(observed||confidenceRank[item.confidence]>=confidenceRank[this.minimumConfidence])}
  private key(item:CapacityForecast){return`capacity-${createHash('sha256').update(`${item.resourceId}|${item.metric}`).digest('hex').slice(0,16)}`}
  private summary(item:CapacityForecast,threshold:number){const current=item.currentPercent===null?'unknown':`${item.currentPercent}%`,projection=item.daysToThreshold===0?`is already at or above the ${threshold}% threshold`:`is projected to reach ${threshold}% in ${item.daysToThreshold} days`;return`${item.name} ${item.metric} utilization is ${current} and ${projection}. The ${item.projectedPercent}% horizon projection has ${item.confidence} confidence from ${item.samples} samples across ${item.spanDays} days.`}
  private async perform(trigger:Trigger){try{const forecast=await this.forecasts.snapshot(),eligible=forecast.items.filter(item=>this.eligible(item,forecast.policy.thresholdPercent)),keys=new Set(eligible.map(item=>this.key(item))),incidents:(Incident|null)[]=[];for(const item of eligible){const state=item.state==='critical'?'not-ready':'at-risk';incidents.push(await this.monitoring.reconcileSystemIncident({key:this.key(item),state,summary:this.summary(item,forecast.policy.thresholdPercent),cooldownSeconds:this.cooldownSeconds,title:item.state==='critical'?`${item.name} ${item.metric} capacity is critical`:`${item.name} ${item.metric} capacity is at risk`}))}for(const incident of this.active()){const key=incident.ruleId.replace(/^system-/,'');if(!keys.has(key))incidents.push(await this.monitoring.reconcileSystemIncident({key,state:'ready',summary:'The capacity condition cleared or no longer meets the configured confidence policy.',cooldownSeconds:this.cooldownSeconds,title:incident.title}))}const state:CapacityAlertState=eligible.some(item=>item.state==='critical')?'critical':eligible.length?'warning':'healthy';this.lastEvaluatedAt=new Date().toISOString();this.lastState=state;this.lastError='';this.eligibleForecasts=eligible.length;return{trigger,state,forecast,incidents,evaluatedAt:this.lastEvaluatedAt}}catch(value){this.lastError=value instanceof Error?value.message:'Capacity alert evaluation failed';throw value}}
}
function integer(value:string|undefined,fallback:number,min:number,max:number){const result=value===undefined?fallback:Number(value);if(!Number.isInteger(result)||result<min||result>max)throw new Error(`Capacity alert setting must be an integer from ${min} to ${max}`);return result}function confidence(value:string):CapacityConfidence{if(value!=='low'&&value!=='medium'&&value!=='high')throw new Error('Capacity alert minimum confidence must be low, medium, or high');return value}
