import type {TelemetryService} from '../telemetry/service.js';
import type {TelemetryPoint,TelemetrySeries,TelemetrySnapshot} from '../telemetry/types.js';
import type {CapacityConfidence,CapacityForecast,CapacityForecastSnapshot,CapacityMetric} from './types.js';

type CapacityPolicy=CapacityForecastSnapshot['policy'];
const dayMs=86_400_000;
const rounded=(value:number,digits=2)=>Number(value.toFixed(digits));
const numeric=(env:NodeJS.ProcessEnv,key:string,fallback:number,min:number,max:number)=>{const value=Number(env[key]||fallback);if(!Number.isFinite(value)||value<min||value>max)throw new Error(`${key} must be between ${min} and ${max}`);return value};
export function capacityPolicyFromEnvironment(env:NodeJS.ProcessEnv=process.env):CapacityPolicy{const policy={thresholdPercent:numeric(env,'SENTINEL_CAPACITY_THRESHOLD_PERCENT',90,50,100),horizonDays:numeric(env,'SENTINEL_CAPACITY_FORECAST_HORIZON_DAYS',30,1,365),warningDays:numeric(env,'SENTINEL_CAPACITY_WARNING_DAYS',30,1,365),criticalDays:numeric(env,'SENTINEL_CAPACITY_CRITICAL_DAYS',7,1,365),minimumSamples:Math.floor(numeric(env,'SENTINEL_CAPACITY_MIN_SAMPLES',7,3,30)),minimumSpanDays:numeric(env,'SENTINEL_CAPACITY_MIN_SPAN_DAYS',6,1,30)};if(policy.criticalDays>policy.warningDays)throw new Error('SENTINEL_CAPACITY_CRITICAL_DAYS cannot exceed SENTINEL_CAPACITY_WARNING_DAYS');return policy}

const metricValue=(point:TelemetryPoint,metric:CapacityMetric)=>metric==='cpu'?point.cpuPercent:metric==='memory'?point.memoryPercent:point.diskPercent;
function regression(points:{time:number;value:number}[]){const origin=points[0].time;const values=points.map(point=>({x:(point.time-origin)/dayMs,y:point.value}));const meanX=values.reduce((sum,item)=>sum+item.x,0)/values.length;const meanY=values.reduce((sum,item)=>sum+item.y,0)/values.length;const denominator=values.reduce((sum,item)=>sum+(item.x-meanX)**2,0);if(!denominator)return{slope:0,rSquared:0};const slope=values.reduce((sum,item)=>sum+(item.x-meanX)*(item.y-meanY),0)/denominator;const intercept=meanY-slope*meanX;const total=values.reduce((sum,item)=>sum+(item.y-meanY)**2,0);const residual=values.reduce((sum,item)=>sum+(item.y-(intercept+slope*item.x))**2,0);return{slope,rSquared:total===0?1:Math.max(0,1-residual/total)}}
function confidence(samples:number,spanDays:number,rSquared:number):CapacityConfidence{if(samples>=21&&spanDays>=20&&rSquared>=.7)return'high';if(samples>=10&&spanDays>=9&&rSquared>=.4)return'medium';return'low'}
export function forecastSeries(series:TelemetrySeries,metric:CapacityMetric,policy:CapacityPolicy):CapacityForecast{const current=metric==='cpu'?series.latest.cpuPercent:metric==='memory'?series.latest.memoryPercent:series.latest.diskPercent;const base={resourceId:series.resourceId,name:series.name,type:series.type,source:series.source,metric,currentPercent:current,slopePercentPerDay:null,projectedPercent:null,daysToThreshold:null,confidence:'low' as CapacityConfidence,samples:0,spanDays:0,rSquared:null};if(current===null)return{...base,state:'insufficient'};const samples=series.points.map(point=>({time:new Date(point.timestamp).getTime(),value:metricValue(point,metric)})).filter((point):point is {time:number;value:number}=>point.value!==null&&Number.isFinite(point.time)).sort((a,b)=>a.time-b.time);const spanDays=samples.length>1?(samples.at(-1)!.time-samples[0].time)/dayMs:0;if(current>=policy.thresholdPercent)return{...base,samples:samples.length,spanDays:rounded(spanDays,1),projectedPercent:current,daysToThreshold:0,state:'critical'};if(samples.length<policy.minimumSamples||spanDays<policy.minimumSpanDays)return{...base,samples:samples.length,spanDays:rounded(spanDays,1),state:'insufficient'};const result=regression(samples);const slope=rounded(result.slope);const rSquared=rounded(result.rSquared);const certainty=confidence(samples.length,spanDays,result.rSquared);if(result.slope<=.05)return{...base,samples:samples.length,spanDays:rounded(spanDays,1),slopePercentPerDay:slope,projectedPercent:rounded(Math.max(0,Math.min(100,current+result.slope*policy.horizonDays)),1),state:'stable',confidence:certainty,rSquared};const days=rounded((policy.thresholdPercent-current)/result.slope,1);const state=days<=policy.criticalDays?'critical':days<=policy.warningDays?'warning':'healthy';return{...base,samples:samples.length,spanDays:rounded(spanDays,1),slopePercentPerDay:slope,projectedPercent:rounded(Math.max(0,Math.min(100,current+result.slope*policy.horizonDays)),1),daysToThreshold:days,state,confidence:certainty,rSquared}}
export function buildCapacityForecast(snapshot:TelemetrySnapshot,mode:'simulation'|'live',policy:CapacityPolicy,evaluatedAt=new Date().toISOString()):CapacityForecastSnapshot{const items=snapshot.series.flatMap(series=>(['cpu','memory','disk'] as CapacityMetric[]).map(metric=>forecastSeries(series,metric,policy)));const actionable=items.filter(item=>item.daysToThreshold!==null);return{mode,evaluatedAt,policy,summary:{resources:snapshot.series.length,forecasts:actionable.length,critical:items.filter(item=>item.state==='critical').length,warning:items.filter(item=>item.state==='warning').length,healthy:items.filter(item=>item.state==='healthy').length,stable:items.filter(item=>item.state==='stable').length,insufficient:items.filter(item=>item.state==='insufficient').length,nearestDays:actionable.length?Math.min(...actionable.map(item=>item.daysToThreshold!)):null},items:items.sort((a,b)=>{const rank={critical:0,warning:1,healthy:2,stable:3,insufficient:4};return rank[a.state]-rank[b.state]||(a.daysToThreshold??Infinity)-(b.daysToThreshold??Infinity)})}}
const escapeLabel=(value:string)=>value.replace(/\\/g,'\\\\').replace(/"/g,'\\"').replace(/\n/g,'\\n');
export class CapacityForecastService{readonly policy:CapacityPolicy;constructor(private readonly telemetry:Pick<TelemetryService,'ready'|'metrics'|'mode'>,env:NodeJS.ProcessEnv=process.env){this.policy=capacityPolicyFromEnvironment(env)}async snapshot(){await this.telemetry.ready;return buildCapacityForecast(this.telemetry.metrics('30d'),this.telemetry.mode(),this.policy)}async prometheus(){const snapshot=await this.snapshot();const lines=['# HELP sentinel_capacity_current_percent Current utilization used by the capacity forecast.','# TYPE sentinel_capacity_current_percent gauge','# HELP sentinel_capacity_days_to_threshold Projected days until the configured utilization threshold.','# TYPE sentinel_capacity_days_to_threshold gauge','# HELP sentinel_capacity_forecast_state Capacity forecast state (1 for the current state).','# TYPE sentinel_capacity_forecast_state gauge'];for(const item of snapshot.items){const labels=`resource_id="${escapeLabel(item.resourceId)}",name="${escapeLabel(item.name)}",type="${item.type}",source="${item.source}",metric="${item.metric}"`;if(item.currentPercent!==null)lines.push(`sentinel_capacity_current_percent{${labels}} ${item.currentPercent}`);if(item.daysToThreshold!==null)lines.push(`sentinel_capacity_days_to_threshold{${labels}} ${item.daysToThreshold}`);lines.push(`sentinel_capacity_forecast_state{${labels},state="${item.state}",confidence="${item.confidence}"} 1`)}return`${lines.join('\n')}\n`}}
