export type Kind = 'frontend' | 'api' | 'container' | 'livenx' | 'livewire';
export type Test = { id: string; name: string; kind: Kind; target: string; critical: boolean; timeoutMs: number };
export type Result = Test & { status: 'passed' | 'failed'; latency: number; detail: string; timestamp: string };
export type Gate = { status: 'ready' | 'blocked'; score: number; passed: number; total: number; criticalFailures: number; minScore: number };
export type Run = { id: string; startedAt: string; duration: number; results: Result[]; gate: Gate };

export type ResourceType = 'node' | 'qemu' | 'lxc' | 'storage';
export type HealthStatus = 'healthy' | 'warning' | 'critical' | 'unknown';
export type ProxmoxResource = {
  id: string;
  type: ResourceType;
  name: string;
  node?: string;
  vmid?: number;
  parentId?: string;
  state: string;
  health: HealthStatus;
  uptimeSeconds?: number;
  cpuPercent?: number;
  memoryUsedBytes?: number;
  memoryTotalBytes?: number;
  diskUsedBytes?: number;
  diskTotalBytes?: number;
};
export type ProxmoxInventory = {
  source: 'simulation' | 'proxmox';
  collectedAt: string;
  clusterName: string;
  resources: ProxmoxResource[];
  summary: {
    nodes: number;
    virtualMachines: number;
    lxcContainers: number;
    storagePools: number;
    runningWorkloads: number;
    stoppedWorkloads: number;
    warnings: number;
  };
};

export type DockerContainer = {
  id: string;
  name: string;
  image: string;
  state: string;
  status: string;
  health: HealthStatus;
  composeProject?: string;
  composeService?: string;
  ports: Array<{ privatePort: number; publicPort?: number; protocol: string }>;
  createdAt: string;
};
export type DockerInventory = {
  source: 'simulation' | 'docker';
  collectedAt: string;
  engineName: string;
  engineVersion?: string;
  containers: DockerContainer[];
  summary: { total: number; running: number; stopped: number; healthy: number; unhealthy: number; composeProjects: number };
};
export type ConnectionStatus = { proxmox: { configured: boolean }; docker: { configured: boolean }; redfish:{configured:boolean;targets:number}; snmp:{configured:boolean;targets:number} };
export type HardwareComponent={id:string;name:string;type:string;health:HealthStatus;value?:number;unit?:string;detail?:string};
export type HardwareDevice={id:string;externalId:string;name:string;source:'redfish'|'snmp';category:'physical_server'|'switch'|'router'|'ups'|'pdu'|'storage_appliance'|'other';health:HealthStatus;status:string;manufacturer?:string;model?:string;serialNumber?:string;firmwareVersion?:string;managementAddress:string;metrics:Record<string,number|undefined>;components:HardwareComponent[];attributes:Record<string,string|number|boolean|null>;collectedAt:string};
export type HardwareInventory={mode:'simulation'|'live';collectedAt:string;devices:HardwareDevice[];summary:{devices:number;servers:number;networkDevices:number;powerDevices:number;healthy:number;warnings:number;critical:number;components:number}};
export type HardwareFinding={id:string;deviceId:string;deviceName:string;kind:string;severity:'warning'|'critical';title:string;detail:string;value?:number;unit?:string;status:'active'|'resolved';suppressed:boolean;firstSeenAt:string;lastSeenAt:string;resolvedAt?:string};
export type MaintenanceWindow={id:string;deviceId:string;reason:string;startsAt:string;endsAt:string;createdAt:string};
export type FirmwareBaseline={deviceId:string;firmwareVersion:string;model:string;serialNumber:string;recordedAt:string};
export type HardwareOperations={findings:HardwareFinding[];maintenanceWindows:MaintenanceWindow[];firmwareBaselines:FirmwareBaseline[];summary:{active:number;critical:number;warnings:number;suppressed:number;maintenance:number;baselines:number}};

export type MonitorProtocol = 'http' | 'tcp' | 'dns';
export type MonitorResult = { id: string; monitorId: string; status: 'up' | 'down'; latencyMs: number; detail: string; checkedAt: string };
export type Monitor = {
  id: string;
  name: string;
  protocol: MonitorProtocol;
  target: string;
  intervalSeconds: number;
  timeoutMs: number;
  enabled: boolean;
  expectedStatus?: number;
  createdAt: string;
  lastResult?: MonitorResult;
  healthScore: number | null;
  uptimePercent: number | null;
};
export type MonitorsResponse = { mode: 'simulation' | 'live'; monitors: Monitor[] };
export type AlertSeverity = 'warning' | 'critical';
export type AlertRule = { id: string; name: string; monitorId: string; failureThreshold: number; cooldownSeconds: number; severity: AlertSeverity; enabled: boolean; suppressedUntil?: string; createdAt: string };
export type Incident = { id: string; ruleId: string; monitorId: string; title: string; summary: string; severity: AlertSeverity; status: 'open' | 'acknowledged' | 'resolved'; occurrences: number; openedAt: string; updatedAt: string; acknowledgedAt?: string; resolvedAt?: string; lastNotificationAt?: string };
export type AlertsResponse = { rules: AlertRule[]; notifications: { mode: 'simulation' | 'live'; webhookConfigured: boolean; emailConfigured: boolean } };
export type TopologyNodeType = 'node' | 'vm' | 'lxc' | 'docker-host' | 'application' | 'container' | 'service';
export type TopologyNode = { id:string; type:TopologyNodeType; name:string; state:string; health:HealthStatus; source:'proxmox'|'docker'|'monitoring'; detail?:string };
export type TopologyEdge = { from:string; to:string; relation:'contains'|'hosts'|'runs'|'monitors'; inferred:boolean };
export type DependencyMapping = { id:string; monitorId:string; resourceId:string; createdAt:string };
export type CorrelationGroup = { id:string; rootNodeId:string; title:string; explanation:string; confidence:number; severity:AlertSeverity; incidentIds:string[]; affectedServices:string[]; evidence:string[] };
export type TopologySnapshot = { collectedAt:string; nodes:TopologyNode[]; edges:TopologyEdge[]; correlations:CorrelationGroup[]; mappings:DependencyMapping[]; summary:{nodes:number;relationships:number;services:number;unhealthyDependencies:number;correlatedGroups:number;unmappedServices:number} };
export type MetricRange='1h'|'6h'|'24h'|'7d'|'30d';
export type RetentionPolicy={days:number;maxResults:number};
export type MetricPoint={timestamp:string;checks:number;failures:number;availabilityPercent:number|null;avgLatencyMs:number|null};
export type MetricSummary={checks:number;failures:number;availabilityPercent:number|null;avgLatencyMs:number|null;p95LatencyMs:number|null};
export type MonitorMetricSeries={monitorId:string;name:string;protocol:MonitorProtocol;currentStatus:'up'|'down'|'pending';summary:MetricSummary;points:MetricPoint[]};
export type MetricsSnapshot={range:MetricRange;start:string;end:string;bucketSeconds:number;retainedResults:number;retention:RetentionPolicy;overall:MetricSummary&{activeIncidents:number;enabledRules:number};series:MonitorMetricSeries[]};

export type TelemetryPoint={timestamp:string;samples:number;cpuPercent:number|null;memoryPercent:number|null;diskPercent:number|null;networkRxBytesPerSecond:number|null;networkTxBytesPerSecond:number|null;diskReadBytesPerSecond:number|null;diskWriteBytesPerSecond:number|null};
export type TelemetrySample={id:string;resourceId:string;name:string;type:'node'|'vm'|'lxc'|'container';source:'proxmox'|'docker';state:string;cpuPercent:number;memoryPercent:number|null;diskPercent:number|null;networkRxBytesPerSecond:number|null;networkTxBytesPerSecond:number|null;diskReadBytesPerSecond:number|null;diskWriteBytesPerSecond:number|null;collectedAt:string};
export type TelemetrySeries={resourceId:string;name:string;type:TelemetrySample['type'];source:TelemetrySample['source'];state:string;latest:TelemetrySample;points:TelemetryPoint[]};
export type TelemetrySnapshot={range:MetricRange;start:string;end:string;bucketSeconds:number;summary:{resources:number;proxmoxResources:number;containers:number;warningResources:number;sampleCount:number};series:TelemetrySeries[]};

export type CiClass='node'|'vm'|'lxc'|'storage'|'docker_host'|'application'|'container'|'service'|'database'|'network'|'physical_server'|'switch'|'router'|'ups'|'pdu'|'storage_appliance'|'other';
export type CiLifecycle='active'|'stale'|'retired';
export type CiCriticality='low'|'medium'|'high'|'critical';
export type ConfigurationItem={id:string;externalId:string;class:CiClass;name:string;source:'proxmox'|'docker'|'monitoring'|'hardware'|'manual';lifecycle:CiLifecycle;status:string;environment:string;owner:string;criticality:CiCriticality;tags:string[];attributes:Record<string,string|number|boolean|null>;firstSeenAt:string;lastSeenAt:string;updatedAt:string;version:number};
export type CmdbRelationship={id:string;fromId:string;toId:string;type:'contains'|'hosts'|'runs_on'|'depends_on'|'monitored_by'|'connected_to';source:ConfigurationItem['source'];createdAt:string};
export type CmdbChange={id:string;ciId:string;action:string;fields:string[];actor:string;changedAt:string};
export type CmdbStatus={mode:'simulation'|'live';intervalSeconds:number;lastReconciledAt:string|null;lastError:string;items:number;relationships:number;stale:number};
export type CmdbSnapshot={status:CmdbStatus;items:ConfigurationItem[];relationships:CmdbRelationship[];changes:CmdbChange[]};
export type LogLevel='debug'|'info'|'warn'|'error'|'critical'|'unknown';
export type LogRange='15m'|'1h'|'6h'|'24h'|'7d';
export type LogEntry={id:string;timestamp:string;level:LogLevel;message:string;source:string;service:string;ciId:string;host:string;labels:Record<string,string>;raw:string};
export type LogSearchResult={mode:'simulation'|'live';query:string;range:LogRange;start:string;end:string;entries:LogEntry[];summary:{total:number;errors:number;warnings:number;sources:number;services:number}};
export type IncidentLogCorrelation=LogSearchResult&{incident:Incident;relatedConfigurationItems:string[]};
